import os
import json
import re
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import anthropic

COMPANIES = [
    "Ameriprise Financial / Columbia Threadneedle Investments",
    "BNY Mellon", "Brown-Forman Corporation", "McKinsey & Company",
    "Meta (Facebook)", "Morgan Stanley", "Royal Bank of Canada (RBC)",
    "Salesforce", "ServiceNow", "The Vanguard Group", "Western Union",
    "Viatris Healthcare", "Yahoo", "Ally Financial", "AON", "Bread Financial",
    "Citizens Bank", "Credit One Bank", "Edward Jones / Jones Financial",
    "Fair Isaac / FICO", "KeyBank", "Moody's Corporation",
    "Northwestern Mutual", "Progressive", "SoFi", "Apple", "Box",
    "Cognizant", "Lam Research", "Lime", "Roblox", "Samsara",
    "SharkNinja", "Veeva Systems", "Avantor", "Biogen", "Lululemon",
    "Paramount Global", "Ulta Beauty", "Chobani", "Performance Food Group",
    "Sazerac", "US Foods", "GlobalFoundries", "Halliburton",
    "Koch Industries", "Marathon Petroleum", "CHS", "Toast"
]

def run_scan():
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    today = datetime.now().strftime("%A, %B %d, %Y")

    system_prompt = f"""You are a senior media intelligence analyst at Signal AI, an enterprise AI-powered reputation risk and media monitoring platform.

Today's date: {today}

Your task: search for news from the past 24 hours about the companies listed below. Identify the TOP 5 companies facing the highest velocity of negative or reputational risk coverage right now.

Focus areas: regulatory enforcement actions, lawsuits and litigation, leadership scandals or departures, layoffs and restructuring, data breaches or security incidents, product failures or recalls, financial distress signals, ESG controversies, negative analyst coverage, or any story a communications team would need to respond to.

After searching, return ONLY a valid JSON object, no markdown, no preamble, no explanation, using EXACTLY this structure:

{{"scan_date":"{datetime.now().strftime('%Y-%m-%d')}","top_5":[{{"rank":1,"company":"Company Name","risk_score":8,"coverage_velocity":"High","key_stories":[{{"headline":"Story headline","source":"Publication","summary":"One sentence summary."}}],"risk_summary":"2-3 sentences on the reputational situation and why it matters to a comms team.","outreach_email":{{"to_role":"Chief Communications Officer","subject":"Email subject line","body":"Full email body. 3-4 short paragraphs. Reference the specific news story as context. Position Signal AI as a solution for enterprise media intelligence and real-time reputation risk monitoring. Professional and empathetic tone, not opportunistic. Soft CTA for a brief call.\\n\\nBest,\\n\\nRich\\nEnterprise Account Executive, Signal AI"}}}}]}}

Companies to scan:
{', '.join(COMPANIES)}"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        system=system_prompt,
        messages=[{
            "role": "user",
            "content": "Search for news from the past 24 hours about all listed companies. Identify the top 5 by negative coverage velocity. Return only valid JSON as specified."
        }]
    )

    full_text = ""
    for block in response.content:
        if hasattr(block, "text"):
            full_text += block.text

    match = re.search(r'\{[\s\S]*\}', full_text)
    if not match:
        raise ValueError("Could not parse scan results from API response.")

    return json.loads(match.group(0))


def format_email_body(data):
    lines = []
    lines.append(f"SIGNAL AI DAILY REPUTATION SCAN")
    lines.append(f"Date: {data['scan_date']}")
    lines.append(f"Top 5 accounts by negative coverage velocity")
    lines.append("=" * 62)
    lines.append("")

    for co in data["top_5"]:
        lines.append(f"{co['rank']}. {co['company'].upper()}")
        lines.append(f"   Risk Score: {co['risk_score']}/10   |   Velocity: {co['coverage_velocity']}")
        lines.append("")
        lines.append("   KEY STORIES:")
        for s in co["key_stories"]:
            lines.append(f"   * {s['headline']} ({s['source']})")
            lines.append(f"     {s['summary']}")
        lines.append("")
        lines.append(f"   SITUATION SUMMARY:")
        lines.append(f"   {co['risk_summary']}")
        lines.append("")
        lines.append(f"   --- DRAFT EMAIL TO {co['outreach_email']['to_role'].upper()} ---")
        lines.append(f"   Subject: {co['outreach_email']['subject']}")
        lines.append("")
        for line in co["outreach_email"]["body"].split("\n"):
            lines.append(f"   {line}")
        lines.append("")
        lines.append("-" * 62)
        lines.append("")

    lines.append("Generated by Signal AI Daily Reputation Scanner")
    return "\n".join(lines)


def send_email(subject, body):
    to_email = os.environ["TO_EMAIL"]
    from_email = os.environ["FROM_EMAIL"]
    app_password = os.environ["GMAIL_APP_PASSWORD"]

    msg = MIMEMultipart()
    msg["From"] = from_email
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(from_email, app_password)
        server.send_message(msg)
    print(f"Email sent to {to_email}")


if __name__ == "__main__":
    print(f"Starting reputation scan — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    data = run_scan()
    top = data["top_5"][0]["company"]
    print(f"Scan complete. Top account: {top}")

    body = format_email_body(data)
    subject = f"Signal AI Reputation Scan — {data['scan_date']} | Top: {top}"
    send_email(subject, body)
    print("Done.")
